export const newsSources = {
    'Top Headlines': 'top-headlines',
    'ABC News': 'abc-news',
    'Associated Press': 'associated-press',
    'BBC News': 'bbc-news',
    'Bleacher Report': 'bleacher-report',
    'Bloomberg': 'bloomberg',
    'Business Insider': 'business-insider',
    'CBS News': 'cbs-news',
    'CNBC': 'cnbc',
    'CNN': 'cnn',
    'Daily Mail': 'daily-mail',
    'ESPN': 'espn',
    'Fortune': 'fortune',
    'Fox News': 'fox-news',
    'Independent': 'independent',
    'MSNBC': 'msnbc',
    'NBC News': 'nbc-news',
    'Politico': 'politico',
    'Reddit /r/all': 'reddit-r-all',
    'Reuters': 'reuters',
    'The Huffington Post': 'the-huffington-post',
    'The New York Times': 'the-new-york-times',
    'The Wall Street Journal': 'the-wall-street-journal',
    'The Washington Post': 'the-washington-post',
    'The Washington Times': 'the-washington-times',
    'Time': 'time'
};